### ISSUE TITLE
03-packaging-installing: avoid hyphen in package name

### ISSUE THREAD

**Issue by tobyhodges** [brownsarahm/python-data-project#56]
In the section "Step 1: Creating a directory" of episode 2, the example command is `mkdir package-name`. Package names with hyphens are invalid so this example should be adjusted, either to `packageName` or something else e.g. `Vehicles` (as seems to be intended based on the text immediately above the example code block).

**Comment by vinisalazar** [comment]
The package name in Ep 03 is currently `conversions`. In Ep 02, however, there is the `mkdir package-name` command. I made some edits to Ep 02 (#75) and edited this command to avoid hyphens.

**Comment by brownsarahm** [comment]
thanks @vinisalazar that is correct and closes it.
