### ISSUE TITLE
07-documentation-with-sphinx: update to reflect changes in `sphinx-quickstart`

### ISSUE THREAD

**Issue by tobyhodges** [brownsarahm/python-data-project#59]
`sphinx-quickstart` no longer asks about setup for automatic API documentation as part of the set of questions asked during initial setup. The lesson material should be updated to reflect this change and show how the learner can configure sphinx to generate the API docs.

**Comment by willfurnass** [comment]
I think if/when PR #68 is merged then the parts of this not addressed by that PR are a dup of Issue #17 so this can then be closed.

**Comment by brownsarahm** [comment]
@willfurnass thanks and I agree, closing this
