### ISSUE TITLE
Improve example code in `03-packaging-installing`

### ISSUE THREAD

**Issue by brownsarahm** [brownsarahm/python-data-project#65]
The example code to be used in `03-packaging-installing` should be more related to scientific computing to be accessible to the target audience.

**Comment by callumrollo** [comment]
I agree, classes are overkill for a packaging tutorial. There are quite a few typos and other minor issues too. I'm happy to go over this lesson if that's ok?

**Comment by brownsarahm** [comment]
A PR for this would be wonderful

**Comment by callumrollo** [comment]
Cool, I'll have a draft PR in by the end of the week.
