### ISSUE TITLE
Maintainer application

### ISSUE THREAD

**Issue by vinisalazar** [brownsarahm/python-data-project#87]
#### 1. Why do you want to be a maintainer of this lesson?
I believe that this lesson is very important to the scientific community, as learning how to package and publish Python code is a valuable skill for many researchers. There are some resources on how to do this in the Internet, but having this available as a Carpentries Incubator lesson makes teaching it much easier. I have made some contributions to this lesson and hope to continue to contribute as a maintainer.

#### 2. What experience with the content of this lesson do you have?
I have developed and packaged a Python application for my MSc research, and am in the process of publishing it. I've had hands-on experience with the topics covered in all episodes of the lesson, from "Setting up a project" to "Testing and continuous integration".

#### 3. What experience in open source maintenance do you have?
I have contributed to a few open source projects, such as [Conda-forge](https://github.com/conda-forge/infomap-feedstock/), [Bioconda](https://github.com/bioconda/bioconda-recipes/pull/25925), and [Biopython](https://github.com/biopython/biopython/pull/3279). I am conscious with Git best practices such as using appropriate branches, writing descriptive commit messages, etc.

#### 4. What Carpentries Experience do you have?
I am a certified Carpentries Instructor and have taught a couple of workshops. I've also contributed to several Carpentries lessons as part of [a project funded by the Python Software Foundation](https://carpentries.org/blog/2021/04/carpentries-python-software-working-group-grant/).

**Comment by brownsarahm** [comment]
Thanks @vinisalazar. I would love to have you as a co-maintainer.  @tobyhodges how can we make that happen?

**Comment by tobyhodges** [comment]
I am delighted to see this happening! As this is not an official lesson there is no formal process for becoming a Maintainer - if @brownsarahm is happy to have you involved, @vinisalazar, then we are good to go.

I have invited Vini to join the Carpentries Incubator organisation, and the Maintainer Team for this lesson. After that invitation is accepted, he should receive _Maintain_-level permissions on this repository and can start the important work of reviewing and merging PRs, triaging issues, etc. If there is anything else that I can do to help, please ping me here again.

**Comment by vinisalazar** [comment]
Thank you @tobyhodges!

**Comment by brownsarahm** [comment]
Thanks, I'm going to close this issue now.
